$background = rgb(000000)
$foreground = rgb(ffffff)

$color0 = rgb(000000)
$color1 = rgb(9f02bc)
$color2 = rgb(da0170)
$color3 = rgb(d35076)
$color4 = rgb(da6e7e)
$color5 = rgb(6e6eda)
$color6 = rgb(eebbd4)
$color7 = rgb(ffffff)
$color8 = rgb(010000)
$color9 = rgb(210725)
$color10 = rgb(761947)
$color11 = rgb(9e7883)
$color12 = rgb(b2999d)
$color13 = rgb(9e9eb2)
$color14 = rgb(e7ceda)
$color15 = rgb(ffffff)
