$background = rgb(030303)
$foreground = rgb(ffc6f0)

$color0 = rgb(030303)
$color1 = rgb(b22888)
$color2 = rgb(c73040)
$color3 = rgb(2565a3)
$color4 = rgb(de3661)
$color5 = rgb(db3679)
$color6 = rgb(327eca)
$color7 = rgb(ff87ff)
$color8 = rgb(111212)
$color9 = rgb(77476a)
$color10 = rgb(865d61)
$color11 = rgb(676b6d)
$color12 = rgb(966b76)
$color13 = rgb(8e717d)
$color14 = rgb(7d8389)
$color15 = rgb(ffc6f0)
