cursor                  #ffffff
cursor_text_color       #ffffff

foreground              #ffffff
background              #000000
selection_foreground    #ffffff
selection_background    #010000
url_color               #da6e7e

color0   #000000
color8   #010000

color1   #9f02bc
color9   #210725

color2   #da0170
color10  #761947

color3   #d35076
color11  #9e7883

color4   #da6e7e
color12  #b2999d

color5   #6e6eda
color13  #9e9eb2

color6   #eebbd4
color14  #e7ceda

color7   #ffffff
color15  #ffffff
