cursor                  #ffffff
cursor_text_color       #ffffff

foreground              #ffffff
background              #110b0c
selection_foreground    #ffffff
selection_background    #6a4750
url_color               #c4c4f0

color0   #110b0c
color8   #6a4750

color1   #5d9ad6
color9   #a2a5a7

color2   #8e65e1
color10  #a7a6aa

color3   #96b8e4
color11  #c5c9ce

color4   #c4c4f0
color12  #d5d5ed

color5   #c0dfef
color13  #e7e9eb

color6   #cdedf2
color14  #daf0f3

color7   #ffffff
color15  #ffffff
