cursor                  #ffffff
cursor_text_color       #ffffff

foreground              #ffffff
background              #1d2523
selection_foreground    #ffffff
selection_background    #799d93
url_color               #d1e28b

color0   #1d2523
color8   #799d93

color1   #6bd65d
color9   #82a77d

color2   #c9da6e
color10  #a7b26c

color3   #b9dd79
color11  #abba91

color4   #d1e28b
color12  #bec699

color5   #e8f1ca
color13  #e6f1c1

color6   #ecf4d6
color14  #e1fc9b

color7   #ffffff
color15  #ffffff
