# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#030303\033\\"
printf "\033]4;1;#b22888\033\\"
printf "\033]4;2;#c73040\033\\"
printf "\033]4;3;#2565a3\033\\"
printf "\033]4;4;#de3661\033\\"
printf "\033]4;5;#db3679\033\\"
printf "\033]4;6;#327eca\033\\"
printf "\033]4;7;#ff87ff\033\\"
printf "\033]4;8;#111212\033\\"
printf "\033]4;9;#77476a\033\\"
printf "\033]4;10;#865d61\033\\"
printf "\033]4;11;#676b6d\033\\"
printf "\033]4;12;#966b76\033\\"
printf "\033]4;13;#8e717d\033\\"
printf "\033]4;14;#7d8389\033\\"
printf "\033]4;15;#ffc6f0\033\\"

# Background
printf "\033]11;#030303\033\\";

# Foreground
printf "\033]10;#ffc6f0\033\\";

# Cursor
printf "\033]12;#ffc6f0\033\\";

# Border
printf "\033]7044;#ffc6f0\033\\";
