# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#050505\033\\"
printf "\033]4;1;#a46390\033\\"
printf "\033]4;2;#a7757a\033\\"
printf "\033]4;3;#82868a\033\\"
printf "\033]4;4;#d69aa9\033\\"
printf "\033]4;5;#d4a9bb\033\\"
printf "\033]4;6;#c3ccd6\033\\"
printf "\033]4;7;#ffffff\033\\"
printf "\033]4;8;#262828\033\\"
printf "\033]4;9;#bb71a5\033\\"
printf "\033]4;10;#d09298\033\\"
printf "\033]4;11;#a1a7ab\033\\"
printf "\033]4;12;#ffbfd2\033\\"
printf "\033]4;13;#ffd2ea\033\\"
printf "\033]4;14;#f3ffff\033\\"
printf "\033]4;15;#ffffff\033\\"

# Background
printf "\033]11;#050505\033\\";

# Foreground
printf "\033]10;#ffffff\033\\";

# Cursor
printf "\033]12;#ffffff\033\\";

# Border
printf "\033]7044;#ffffff\033\\";
