# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#110b0c\033\\"
printf "\033]4;1;#828486\033\\"
printf "\033]4;2;#868588\033\\"
printf "\033]4;3;#9ea1a5\033\\"
printf "\033]4;4;#ababbe\033\\"
printf "\033]4;5;#b9bbbc\033\\"
printf "\033]4;6;#afc0c3\033\\"
printf "\033]4;7;#ffffff\033\\"
printf "\033]4;8;#6a4750\033\\"
printf "\033]4;9;#a2a5a7\033\\"
printf "\033]4;10;#a7a6aa\033\\"
printf "\033]4;11;#c5c9ce\033\\"
printf "\033]4;12;#d5d5ed\033\\"
printf "\033]4;13;#e7e9eb\033\\"
printf "\033]4;14;#daf0f3\033\\"
printf "\033]4;15;#ffffff\033\\"

# Background
printf "\033]11;#110b0c\033\\";

# Foreground
printf "\033]10;#ffffff\033\\";

# Cursor
printf "\033]12;#ffffff\033\\";

# Border
printf "\033]7044;#ffffff\033\\";
