# Generated by hellwal

wallpaper='/home/caldecrack/.config/assets/wallpapers/Bocchi.png'

background='030303'
foreground='ffc6f0'
cursor='ffc6f0'
border='ffc6f0'

color0='030303'
color1='b22888'
color2='c73040'
color3='2565a3'
color4='de3661'
color5='db3679'
color6='327eca'
color7='ff87ff'
color8='111212'
color9='77476a'
color10='865d61'
color11='676b6d'
color12='966b76'
color13='8e717d'
color14='7d8389'
color15='ffc6f0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
