# Generated by hellwal

wallpaper='/home/caldecrack/.config/assets/wallpapers/arlecchino.jpeg'

background='110b0c'
foreground='ffffff'
cursor='ffffff'
border='ffffff'

color0='110b0c'
color1='828486'
color2='868588'
color3='9ea1a5'
color4='ababbe'
color5='b9bbbc'
color6='afc0c3'
color7='ffffff'
color8='6a4750'
color9='a2a5a7'
color10='a7a6aa'
color11='c5c9ce'
color12='d5d5ed'
color13='e7e9eb'
color14='daf0f3'
color15='ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
