# Generated by hellwal

wallpaper='/home/caldecrack/.config/assets/wallpapers/Bocchi.png'

background='050505'
foreground='ffffff'
cursor='ffffff'
border='ffffff'

color0='050505'
color1='a46390'
color2='a7757a'
color3='82868a'
color4='d69aa9'
color5='d4a9bb'
color6='c3ccd6'
color7='ffffff'
color8='262828'
color9='bb71a5'
color10='d09298'
color11='a1a7ab'
color12='ffbfd2'
color13='ffd2ea'
color14='f3ffff'
color15='ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
