source = /home/caldecrack/.config/hypr/state/current_wallpaper.conf

ipc = on
splash = off

wallpaper {
  monitor =
  path = $current_wallpaper
}

wallpaper {
  monitor = HDMI-A-1
  path = $current_wallpaper
}
