ipc = on

splash = off

wallpaper {
  monitor =
  path = /home/caldecrack/.config/shared-assets/wallpapers/frieren_underwater.png
}

wallpaper {
  monitor = HDMI-A-1
  path = /home/caldecrack/.config/shared-assets/wallpapers/frieren_underwater.png
}
