#!/usr/bin/env sh
# Variables - Generated by matugen

background='{{ colors.background.default.hex_stripped }}'
foreground='{{ colors.on_background.default.hex_stripped }}'
cursor='{{ colors.primary.default.hex_stripped }}'
border='{{ colors.outline.default.hex_stripped }}'

color0='{{ colors.surface.default.hex_stripped }}'
color1='{{ colors.error.default.hex_stripped }}'
color2='{{ colors.tertiary.default.hex_stripped }}'
color3='{{ colors.secondary.default.hex_stripped }}'
color4='{{ colors.primary.default.hex_stripped }}'
color5='{{ colors.primary_container.default.hex_stripped }}'
color6='{{ colors.secondary_container.default.hex_stripped }}'
color7='{{ colors.on_surface.default.hex_stripped }}'
color8='{{ colors.surface_variant.default.hex_stripped }}'
color9='{{ colors.on_error_container.default.hex_stripped }}'
color10='{{ colors.on_tertiary_container.default.hex_stripped }}'
color11='{{ colors.on_secondary_container.default.hex_stripped }}'
color12='{{ colors.on_primary_container.default.hex_stripped }}'
color13='{{ colors.tertiary_container.default.hex_stripped }}'
color14='{{ colors.secondary.default.hex_stripped }}'
color15='{{ colors.on_background.default.hex_stripped }}'

export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
