local cfg = require("config.programs")

hl.on("hyprland.start", function()
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("hyprlock")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("mpc add / && mpc play && mpc pause && sleep 1 && " .. cfg.bar .. " && /usr/bin/mpdris2-rs")
	hl.exec_cmd("squeekboard")
	hl.exec_cmd("hyprsunset")
end)
